<package format="2">
  <name>ugv_gazebo</name>
  <version>0.0.1</version>
  <description>This package provides Gazebo simulation support, including the world and the model.</description>
  <maintainer email="dudulrx@todo.todo">dudulrx</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>controller_manager</depend>
  <depend>position_controllers</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>robot_state_publisher</depend>
  <depend>rviz2</depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_sim</depend>
  <export>
    <architecture_independent />
    <build_type>ament_cmake</build_type>
  </export>
</package>
