/**
 * Generate the Datacore static fixture (`src/data/datacore-corpus.ts`) from the
 * corpus registry + markdown bodies (disk or git history).
 *
 *   npx tsx db/hangar/gen-datacore-corpus.ts
 *
 * Then regenerate seed:
 *   npx tsx db/hangar/gen-seed.ts --out db/hangar/seed.sql
 *
 * The fixture is the hangar.ts equivalent for research — offline fallback and
 * seed baseline. Runtime Postgres remains canonical when healthy.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { CORPUS_BRIEFINGS, CORPUS_PACKS } from './research-corpus-registry';
import { CORPUS_ROOT, corpusSourceExists, readCorpusText } from './research-corpus-resolve';

const OUT = path.join(CORPUS_ROOT, 'src/data/datacore-corpus.ts');

function tsString(value: string): string {
  return JSON.stringify(value);
}

function main() {
  const briefings: {
    id: string;
    title: string;
    href: string;
    source: string;
    kind: 'research' | 'plan';
    summary: string;
    tags: string[];
    aliases?: string[];
    packId?: string;
    capturedAt: string;
    bodyMarkdown: string;
    repoPath: string | null;
  }[] = [];

  for (const meta of CORPUS_BRIEFINGS) {
    if (!corpusSourceExists(meta.source)) {
      throw new Error(`Missing source for briefing '${meta.id}': ${meta.source}`);
    }
    const body = readCorpusText(meta.source);
    if (!body.trim()) {
      throw new Error(`Empty body for briefing '${meta.id}': ${meta.source}`);
    }
    briefings.push({
      id: meta.id,
      title: meta.title,
      href: meta.href,
      source: meta.source,
      kind: meta.kind,
      summary: meta.summary,
      tags: meta.tags,
      ...(meta.aliases ? { aliases: meta.aliases } : {}),
      ...(meta.packId ? { packId: meta.packId } : {}),
      capturedAt: meta.capturedAt,
      bodyMarkdown: body,
      // Provenance for plan (and research that still has a known path).
      repoPath: meta.source,
    });
  }

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * Datacore research corpus fixture — offline / seed baseline.');
  lines.push(' * Generated by `npx tsx db/hangar/gen-datacore-corpus.ts`. Do not hand-edit bodies.');
  lines.push(' * Postgres `briefings` / `briefing_packs` are canonical when the DB is healthy.');
  lines.push(' */');
  lines.push("import type { DatacoreBriefingRow, DatacorePack } from '@/lib/datacore-model';");
  lines.push('');
  lines.push('export const DATACORE_CORPUS_PACKS: DatacorePack[] = [');
  for (const p of CORPUS_PACKS) {
    lines.push('  {');
    lines.push(`    id: ${tsString(p.id)},`);
    lines.push(`    title: ${tsString(p.title)},`);
    lines.push(`    code: ${tsString(p.code)},`);
    lines.push(`    summary: ${tsString(p.summary)},`);
    lines.push(`    hubBriefingId: ${tsString(p.hubBriefingId)},`);
    lines.push(`    topics: ${JSON.stringify(p.topics)},`);
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');
  lines.push('export const DATACORE_CORPUS_BRIEFINGS: DatacoreBriefingRow[] = [');
  for (const b of briefings) {
    lines.push('  {');
    lines.push(`    id: ${tsString(b.id)},`);
    lines.push(`    title: ${tsString(b.title)},`);
    lines.push(`    href: ${tsString(b.href)},`);
    lines.push(`    source: ${tsString(b.source)},`);
    lines.push(`    kind: ${tsString(b.kind)},`);
    lines.push(`    summary: ${tsString(b.summary)},`);
    lines.push(`    tags: ${JSON.stringify(b.tags)},`);
    if (b.aliases) lines.push(`    aliases: ${JSON.stringify(b.aliases)},`);
    if (b.packId) lines.push(`    packId: ${tsString(b.packId)},`);
    lines.push(`    capturedAt: ${tsString(b.capturedAt)},`);
    lines.push(`    bodyMarkdown: ${tsString(b.bodyMarkdown)},`);
    lines.push(
      b.repoPath === null ? '    repoPath: null,' : `    repoPath: ${tsString(b.repoPath)},`,
    );
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');

  writeFileSync(OUT, `${lines.join('\n')}\n`, 'utf8');
  console.log(
    JSON.stringify({
      out: path.relative(CORPUS_ROOT, OUT).replace(/\\/g, '/'),
      packs: CORPUS_PACKS.length,
      briefings: briefings.length,
      bytes: briefings.reduce((n, b) => n + Buffer.byteLength(b.bodyMarkdown, 'utf8'), 0),
    }),
  );
}

main();
